name: Discord Release Notification

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  github-releases-to-discord:
    name: Post Release Changelog to Discord
    runs-on: ubuntu-latest
    steps:
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "8141549"
          username: ${{ github.event.repository.name }}
          footer_timestamp: true
