name: Discord Commit

on:
  workflow_call:
    secrets:
      DISCORD_COMMIT_WEBHOOK:
        required: true

jobs:
  notify:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Notify Discord
        uses: Qbox-project/pipeline-pling@v1
        with:
          webhook-url: ${{ secrets.DISCORD_COMMIT_WEBHOOK }}
          accent-color: "#7c3aed"
